// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoalNo4.Entities;

#nullable disable

namespace SoalNo4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SoalNo4.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<long>("Salary")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e63d57d-b744-4628-8c7c-c918b1e21e4f"),
                            Email = "chandra@gmail.com",
                            Name = "Chandra",
                            Phone = 12345678L,
                            Salary = 2000000L
                        },
                        new
                        {
                            Id = new Guid("4b7843dd-4372-4b64-b487-5e33b0305862"),
                            Email = "Dodi@gmail.com",
                            Name = "Dodi",
                            Phone = 12245678L,
                            Salary = 4000000L
                        },
                        new
                        {
                            Id = new Guid("172862ec-f69c-4be2-8e5f-e60bed9ff1ae"),
                            Email = "agus@gmail.com",
                            Name = "Agus",
                            Phone = 12366678L,
                            Salary = 3000000L
                        },
                        new
                        {
                            Id = new Guid("d3d7ac4c-fa2c-448c-8030-beee0ba297d8"),
                            Email = "taufik@gmail.com",
                            Name = "Taufik",
                            Phone = 12345888L,
                            Salary = 6000000L
                        },
                        new
                        {
                            Id = new Guid("feab6128-b8ce-478e-bd28-b0e7e3713547"),
                            Email = "retno@gmail.com",
                            Name = "Retno",
                            Phone = 123433333L,
                            Salary = 5000000L
                        },
                        new
                        {
                            Id = new Guid("da509fee-a85c-4e3a-85a5-1a4cdce90d99"),
                            Email = "tyas@gmail.com",
                            Name = "Tyas",
                            Phone = 15555678L,
                            Salary = 2400000L
                        },
                        new
                        {
                            Id = new Guid("51903878-fc9c-4412-8ec5-6247f0d2fe3b"),
                            Email = "ryan@gmail.com",
                            Name = "Ryan",
                            Phone = 1111345678L,
                            Salary = 7100000L
                        },
                        new
                        {
                            Id = new Guid("48ec61b4-e38c-4442-bb5c-1eaddcff6bc4"),
                            Email = "rino@gmail.com",
                            Name = "Rino",
                            Phone = 14444678L,
                            Salary = 3200000L
                        },
                        new
                        {
                            Id = new Guid("9749a740-c5d3-4e80-b2d4-accedd084124"),
                            Email = "aji@gmail.com",
                            Name = "Aji",
                            Phone = 66665678L,
                            Salary = 9000000L
                        },
                        new
                        {
                            Id = new Guid("f4e554a0-14a8-4013-9cd8-577f1430a70a"),
                            Email = "ani@gmail.com",
                            Name = "Ani",
                            Phone = 18885678L,
                            Salary = 3500000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
